### PR TITLE
Migrate from Travis to Github Actions

### LINKED ISSUE #8: Support for Python 3.8 and 3.9
Hello,

Do you plan to provide support for Python 3.8 and 3.9?

Trying to install it on Debian Buster returns error below.

```bash
docker run -it python:3.9-buster sh
pip install pcst-fast
# ERROR: Could not find a version that satisfies the requirement pcst-fast
# ERROR: No matching distribution found for pcst-fast
```

I am not qualified in C++ or Python bindings, but let me know if I can help.

Thank you for your work!

### PR DESCRIPTION
**Pull request by adrien-berchet**
Fixes #8

### CODE REVIEW

**Comment by adrien-berchet** [comment]
Please note that you need to set the `PYPI_PASSWORD` to your Pypi token before merging this.

**Comment by adrien-berchet** [comment]
I just noticed that testing the wheels with Pypy on Windows takes a lot of time. I guess it is because of the compilation of the Numpy package.
If you think it can be an issue to have a so long CI in PRs I can disable the `pull_request` trigger, so the wheels are only built on the main branch and tags.

**Comment by alexlenail** [comment]
Let's give it a try. I added the secrets.

**Comment by adrien-berchet** [comment]
Thanks @alexlenail !
Now you just have to create a new release to see if all the wheels and sources are properly pushed to Pypi.

**Comment by adrien-berchet** [comment]
Hi @alexlenail 
I see that the push to Pypi failed, could you check the value you set in the `PYPI_PASSWORD` variable please?

**Comment by alexlenail** [comment]
Hi @adrien-berchet 
I updated the pypi token, and I think it should work now. How do I test run the pypi release action again, without creating a new tag? Github is upset at me if I try to re-release the same commit as a new "release" (1.0.9)

**Comment by adrien-berchet** [comment]
In the workflow you are supposed to have a `Re-run jobs` button in the top left corner (just on the left of the `Latest #2` button) if you have proper permissions. With it you can re-run the failed jobs.

**Comment by adrien-berchet** [comment]
Hi @alexlenail 
I think my answer was not relevant for your question, sorry.
I guess you can just remove both the tag and the github release and recreate them?

**Comment by alexlenail** [comment]
I have deleted the release and the tag, made an arbitrary commit, and tagged it. The workflow should run again, and I should have the correct password in there now.

**Comment by adrien-berchet** [comment]
I can't see the tag on the last commit so the publish job did not trigger.

**Comment by adrien-berchet** [comment]
@alexlenail can you try to create a new tag to trigger the publish job please? (and sorry for all these back and forth...)

**Comment by alexlenail** [comment]
It's us who should apologize for not supporting this package -- I'm grateful for your PR and help.

Let's see whether this latest one works.

**Comment by adrien-berchet** [comment]
No problem, you're welcome :)

The last attempt (kinda) worked! :tada: 
Thanks for your help!

There are 2 issues though:
1. the package version is `1.0.7` instead of `1.0.8` because it is hardcoded in `setup.py` and we forgot to change it.
2. the building process of the wheels is super long because Numpy has to be built from sources for a few platform/arch (installing Numpy is required because I activated the tests of each built wheel).

I am going to fix these in a new PR so the future releases should be cleaner and faster.

**Pull request merged**
